# Generated by Django 4.2.17 on 2026-02-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('aggregating', 'Aggregating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('participants_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_accuracy', models.FloatField(default=0.0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('model_weights', models.JSONField(default=dict)),
                ('fl_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_models', to='federation.flround')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_accuracy', models.FloatField(default=0.0)),
                ('model_weights', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fl_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_models', to='federation.flround')),
            ],
        ),
    ]
