# Generated by Django 5.2.11 on 2026-02-20 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_bg_color', models.CharField(default='#E3F2FD', help_text='Light mode background color', max_length=7)),
                ('light_text_color', models.CharField(default='#01579B', help_text='Light mode text color', max_length=7)),
                ('light_accent_color', models.CharField(default='#0288D1', help_text='Light mode accent/primary color', max_length=7)),
                ('light_card_bg', models.CharField(default='#FFFFFF', help_text='Light mode card background', max_length=7)),
                ('dark_bg_color', models.CharField(default='#1B4332', help_text='Dark mode background color', max_length=7)),
                ('dark_text_color', models.CharField(default='#D8F3DC', help_text='Dark mode text color', max_length=7)),
                ('dark_accent_color', models.CharField(default='#52B788', help_text='Dark mode accent/primary color', max_length=7)),
                ('dark_card_bg', models.CharField(default='#2D6A4F', help_text='Dark mode card background', max_length=7)),
                ('preferred_theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System)')], default='auto', help_text='User preferred default theme', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Theme Settings',
                'verbose_name_plural': 'User Theme Settings',
            },
        ),
    ]
