# Generated by Django 5.2.10 on 2026-01-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('global_accuracy', models.FloatField(default=0.0)),
                ('global_loss', models.FloatField(default=0.0)),
                ('participating_hospitals', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Federated Learning Round',
                'verbose_name_plural': 'Federated Learning Rounds',
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='LocalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0)),
                ('loss', models.FloatField(default=0.0)),
                ('training_samples', models.IntegerField(default=0)),
                ('epochs_trained', models.IntegerField(default=1)),
                ('training_started', models.DateTimeField(auto_now_add=True)),
                ('training_completed', models.DateTimeField(blank=True, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('federated_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_models', to='federated.federatedround')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_models', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Local Model',
                'verbose_name_plural': 'Local Models',
                'ordering': ['-training_started'],
            },
        ),
    ]
